#!/usr/bin/env bash

# Enables new Docker build UI
export DOCKER_BUILDKIT=1

DOCKER_WORKDIR_PATH=/usr/src/app
DOCKER_CURRENT_USER="--user $(id -u):$(id -g) -e USER=$(id -u)"
DOCKER_XDISPLAY="-v /tmp/.X11-unix/:/tmp/.X11-unix/ -v /dev/shm:/dev/shm -e DISPLAY"
DOCKER_KVM="--device /dev/kvm"
DOCKER_SOUND="--device /dev/snd"
DOCKER_TUN="--device=/dev/net/tun --cap-add NET_ADMIN"

dk_mount_point() {
  echo "-v $(pwd):$DOCKER_WORKDIR_PATH -w $DOCKER_WORKDIR_PATH"
}

dk_user_keys() {
  echo "-v $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro -v $HOME/.ssh/id_rsa:/root/.ssh/id_rsa:ro"
}

# DOCKER

## dk-clear-logs
## Description
##   Clear all containers logs
## Usage:
##   $ dk-clear-logs

alias dk-clear-logs='sudo sh -c "truncate -s 0 /var/lib/docker/containers/*/*-json.log"'


## dkrit
## Description
##   docker run with interactive
## Usage:
##   $ dkrit <image>[:<tag>] ...
##   $ dkrit <image uri> ...

dkrit(){

  docker run -it $@
}

## dkxit
## Description
##   docker run with interactive
## Usage:
##   $ dkxit <image>[:<tag>] ...
##   $ dkxit <image uri> ...

alias dkxit="docker exec -it"

## dkrtmp
## Description
##   runs a temporary container from a image (local or remote)
## Usage:
##   $ dkrtmp <image>[:<tag>]
##   $ dkrtmp <image uri>

alias dkrtmp="dkrit --rm"

## dkrtmpuser
## Description
##   runs a temporary container from a image (local or remote)
##   with the current dir and user configured
## Usage:
##   $ dkrtmpuser <image>[:<tag>] [<shell|command>]
##   $ dkrtmpuser <image uri> [<shell|command>]

dkrtmpuser() {
  dkrtmp $DOCKER_CURRENT_USER $(dk_mount_point) $@
}

## dkrtmpnouser
## Description
##   runs a temporary container from a image (local or remote)
##   only with the current dir mounted
## Usage:
##   $ dkrtmpnouser <image>[:<tag>] [<shell|command>]
##   $ dkrtmpnouser <image uri> [<shell|command>]

dkrtmpnouser() {
  dkrtmp $(dk_mount_point) $@
}

## dkrtmproot
## Description
##   runs a temporary container from a image (local or remote)
##    with the current dir and root configured
## Usage:
##   $ dkrtmproot <image>[:<tag>] [<shell|command>]
##   $ dkrtmproot <image uri> [<shell|command>]

dkrtmproot() {
  dkrtmp -u root $(dk_mount_point) $@
}

## RAW docker images
for IMAGE_NAME in $DOCKER_PRESET_IMAGES
do
  alias dkr-$IMAGE_NAME-user="dkrtmpuser $IMAGE_NAME:latest"
  alias dkr-$IMAGE_NAME-root="dkrtmproot $IMAGE_NAME:latest"
  alias dkr-$IMAGE_NAME-nouser="dkrtmpnouser $IMAGE_NAME:latest"
  alias dkr-$IMAGE_NAME="dkr-$IMAGE_NAME-user"
done

###############################################
dkcpcredentials() {
  docker cp ~/.gitconfig $1:/root/.gitconfig
  docker cp ~/.ssh/id_rsa $1:/root/.ssh/id_rsa
}


dkb(){
  docker build $@
}

dk-img-local() {
  docker images -q "local/$1:latest"
}

dk-ctx(){
  if [[ $# -eq 1 ]]; then
    docker context use $1
  else
    docker context show
  fi
}
