#!/usr/bin/env bash

DEFAULT_PROJECT_ENVS="$HOME/.config/dotfiles/custom"

# load_client_env
# Description
#   Loads the project config file from `./custom/`
# Usage:
# load_client_env <project-file>

load_client_env() {
  export CURRENT_PROJECT=$1
  export WORKDIR="$DEFAULT_PROJECTS_FOLDER/$CURRENT_PROJECT"

  source "$DEFAULT_PROJECT_ENVS/$CURRENT_PROJECT"
  [ ! -d "$WORKDIR" ] && mkdir $WORKDIR
  cd $WORKDIR
}

# prj_create_def
# Description
#   Creates the project config file inside `./custom/`
# Usage:
# prj_create_def <project-file>

prj_create_def() {
  cp "$DEFAULT_PROJECT_ENVS/.example" "$DEFAULT_PROJECT_ENVS/$1"
  echo "$EDITOR $DEFAULT_PROJECT_ENVS/$1"

  # reload aliases
  prj_def_aliases
}

# prj_def_alias
# Description
#   Creates the aliases for the project

prj_def_alias() {
  project=$(basename $1)
  [ -f $1 ] && alias lenv-$project="load_client_env $project"
}


# prj_def_aliases
# Description
#   Loads and create the aliases for all projects config files

prj_def_aliases() {
  for script in "$DEFAULT_PROJECT_ENVS"/*; do
    prj_def_alias $script
  done
}

# prj_touch
# Description
#   touch file inside of the current project folder
# Usage:
#   prj_touch <filename>

prj_touch() {
  local filename=$1

  fullpath="${WORKDIR}/$filename"

  [ ! -f "$fullpath" ] && touch $fullpath

  echo $fullpath
}

prj_cur_folder() {
  echo "$CURRENT_PROJECT-$(basename $PWD)"
}

prj_def_aliases
